In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
np.sqrt(np.dot(b-a,b-a))

5.196152422706632

In [4]:
print(((((b[0]-a[0])**2 + (b[1]-a[1])**2 + (b[2]-a[2])**2 ))**(1/2)))

5.196152422706632


In [12]:
X = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])

In [13]:
X

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [14]:
cluster_group = np.array([0,1,1,0,0])
np.unique(cluster_group)

array([0, 1])

In [15]:
for type in np.unique(cluster_group):
    print(type)

0
1


In [16]:
X[cluster_group == 0]

array([[1, 2],
       [4, 5],
       [5, 6]])

In [17]:
X[cluster_group == 0].mean(axis=0)

array([3.33333333, 4.33333333])

In [19]:
for type in np.unique(cluster_group):
    print(X[cluster_group==type].mean(axis=0))


[3.33333333 4.33333333]
[2.5 3.5]
