In [1]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('/home/jatin/Practise_ML-2/Feature_Engineering/Feature_Selection/Wrapper_Method/Iris.csv',index_col='Id')
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
X = df.iloc[:,0:-1]
Y = df.iloc[:,-1]


In [15]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                          
1             5.1           3.5            1.4           0.2
2             4.9           3.0            1.4           0.2
3             4.7           3.2            1.3           0.2
4             4.6           3.1            1.5           0.2
5             5.0           3.6            1.4           0.2

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X,Y)

RandomForestClassifier()

In [17]:
rf.feature_importances_

array([0.09017939, 0.02974861, 0.45404573, 0.42602627])

In [18]:
X.drop(columns='SepalWidthCm',inplace=True)
X.head()

SepalLengthCm  PetalLengthCm  PetalWidthCm
Id                                            
1             5.1            1.4           0.2
2             4.9            1.4           0.2
3             4.7            1.3           0.2
4             4.6            1.5           0.2
5             5.0            1.4           0.2

In [19]:
rf = RandomForestClassifier()
rf.fit(X,Y)

RandomForestClassifier()

In [20]:
rf.feature_importances_

array([0.18971343, 0.41015293, 0.40013364])

In [22]:
X

SepalLengthCm  PetalLengthCm  PetalWidthCm
Id                                             
1              5.1            1.4           0.2
2              4.9            1.4           0.2
3              4.7            1.3           0.2
4              4.6            1.5           0.2
5              5.0            1.4           0.2
..             ...            ...           ...
146            6.7            5.2           2.3
147            6.3            5.0           1.9
148            6.5            5.2           2.0
149            6.2            5.4           2.3
150            5.9            5.1           1.8

[150 rows x 3 columns]

In [23]:
X.drop(columns='SepalLengthCm',inplace=True)

In [24]:
rf = RandomForestClassifier()
rf.fit(X,Y)

RandomForestClassifier()

In [25]:
rf.feature_importances_

array([0.49309419, 0.50690581])

In [26]:
X

PetalLengthCm  PetalWidthCm
Id                              
1              1.4           0.2
2              1.4           0.2
3              1.3           0.2
4              1.5           0.2
5              1.4           0.2
..             ...           ...
146            5.2           2.3
147            5.0           1.9
148            5.2           2.0
149            5.4           2.3
150            5.1           1.8

[150 rows x 2 columns]

In [27]:
X.drop(columns='PetalLengthCm',inplace=True)

In [28]:
rf = RandomForestClassifier()
rf.fit(X,Y)

RandomForestClassifier()

In [29]:
rf.feature_importances_

array([1.])

### Scikit_Learn_Implementation

In [33]:
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('/home/jatin/Practise_ML-2/Feature_Engineering/Feature_Selection/Wrapper_Method/Iris.csv',index_col='Id')

X = df.drop(columns=['Species'],axis=1)
Y = df['Species']

model = RandomForestClassifier()

rfe = RandomForestClassifier()

rfe = RFE(estimator=model,n_features_to_select=1)

rfe.fit(X,Y)

ranking = rfe.ranking_
print("Feature_Ranking:")

for i,feature in enumerate(X.columns):
    print(f"{feature}:{ranking[i]}")

Feature_Ranking:
SepalLengthCm:3
SepalWidthCm:4
PetalLengthCm:1
PetalWidthCm:2
